# Please refer to https://dev.poktroll.com/configs/relayminer_config for documentation.
signing_key_name: key-for-relayminer1
smt_store_path: smt_stores
pocket_node:
  query_node_rpc_url: tcp://poktrolld:26657
  query_node_grpc_url: tcp://poktrolld:26658
  tx_node_rpc_url: tcp://poktrolld:26657
proxies:
  - proxy_name: http-proxy
    type: http
    host: 0.0.0.0:8545
suppliers:
  - service_id: 0021
    type: http
    service_config:
      url: http://YOUR_NODE_IP_OR_HOST # Local or remote Ethereum RPC endpoint to forward relays to
    proxy_names:
      - http-proxy
    hosts:
      - http://YOUR_NODE_IP_OR_HOST:8545 # External IP address or hostname of your relay miner
metrics:
  enabled: true
  addr: :9090
